Added javascript unit tests

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -1,5 +1,19 @@
 #!/bin/sh
 
+# Check that unit tests pass
+
+CURRENT_BRANCH=$(git symbolic-ref --short head)
+
+if [[ $CURRENT_BRANCH = "main" ]]; then
+	npm run test
+	result=$?
+	if ! $?; then
+		echo "Failed unit tests. Not pushing!" >&2
+		exit 1
+	fi
+fi
+
+# Run spellcheck on all markdown files
 TEMP_DICT="/tmp/candidate_wordlist.txt"
 PERM_DICT=".wordlist.txt"
 
@@ -14,6 +28,10 @@ if [ $? -ne 0 ]; then
 		echo "Spellcheck failed"
 		exit 1
 	fi
+
+	# Amend the commit with the updated dictionary
+	git add $PERM_DICT
+	git commit --amend --no-edit
 fi
 
 echo "Spellcheck passed"
